# file: 1_provision.yml
---
# https://www.terraform.io/docs/providers/aws/index.html


- name: Provision Openstack Infrastucture using Terraform 
  hosts: localhost
  roles:
  - { role: openstack.infra, tags: ["tf_create"] }

- name: Configure proxy to allow access to workstations
  hosts: proxy
  become: true
  tasks:
  - name: wait for proxy to be ready 
    wait_for:
      host: "{{ workshop_prefix }}.proxy.{{ domain_name }}"
      port: 22
      state: started
      timeout: 300

  - name: add nginx
    dnf:
      name: nginx
      state: latest

# {{workshop_prefix}}.tower.<student number>.redhatgov.io:8888
# Username: ec2-user
# Password: redhat!@#

...
